# Generated by Django 4.2 on 2023-04-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placasdevideo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchvga',
            old_name='precovista',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='searchvga',
            old_name='precoprazo',
            new_name='valor_preco_prazo',
        ),
    ]
