# Generated by Django 4.2 on 2023-04-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placasdevideo', '0003_remove_searchvga_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placasdevideo.searchvga')),
            ],
        ),
    ]
