# Generated by Django 4.2 on 2023-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placasdevideo', '0004_precomedio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecoMedio',
        ),
    ]
