# Generated by Django 4.2 on 2023-04-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placasdevideo', '0005_delete_precomedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchvga',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='searchvga',
            name='valor_preco_prazo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
