# Generated by Django 4.2 on 2023-05-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placasdevideo', '0007_searchvga_preco_antigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchvga',
            name='preco_antigo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
