# Generated by Django 4.2 on 2023-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcoolers',
            name='ativo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
