# Generated by Django 4.2 on 2023-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolers', '0002_searchcoolers_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcoolers',
            name='ativo',
        ),
    ]
