# Generated by Django 4.2 on 2023-05-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmemory',
            name='preco_antigo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
